name: Manual Deploy with Inputs

on:
  workflow_dispatch:
    inputs:
      Message:
        description: 'Deploy PPE'
        type: string
        required: false
        default: ''
      Anonymous:
        description: 'Anonymous'
        type: boolean
        default: false
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Display Inputs
      run: |
        if [ -z "${{ github.event.inputs.Message }}" ]; then
          echo "Message: No message provided"
        else
          echo "Message: ${{ github.event.inputs.Message }}"
        fi
        echo "Anonymous: ${{ github.event.inputs.Anonymous }}"
      
    - name: Conditional Step
      if: ${{ github.event.inputs.Anonymous }}
      run: |
        echo "Running in anonymous mode"

    - name: Non-Anonymous Step
      if: ${{ !github.event.inputs.Anonymous }}
      run: |
        echo "Running with user identification"
