name: Manual Deploy with Inputs

on:
  workflow_dispatch:
    inputs:
      InfoMessage:
        description: 'Deploy PPE'
        type: string
        required: false
        default: ''
        
      Anonymous:
        description: 'Anonymous'
        type: boolean
        default: false
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Display Start Message
      run: echo "Starting the deployment process..."

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Display Inputs
      run: |
        echo "Info Message: ${{ github.event.inputs.InfoMessage }}"
        echo "Anonymous: ${{ github.event.inputs.Anonymous }}"
      
    - name: Conditional Step for Anonymous
      if: ${{ github.event.inputs.Anonymous }}
      run: |
        echo "Running in anonymous mode"

    - name: Conditional Step for Non-Anonymous
      if: ${{ !github.event.inputs.Anonymous }}
      run: |
        echo "Running with user identification"
