name: Manual Deploy with Inputs

on:
  workflow_dispatch:
    inputs:
      DeployEnvironment:
        description: 'Choose deployment environment'
        type: choice
        required: true
        options:
          - PPE
          - PROD
      InfoMessage:
        description: 'Select the Customers to deploy'
        type: string
        required: false
        default: 'Select the customers to deploy'
      Anonymous_PPE:
        description: 'Anonymous_PPE'
        type: boolean
        default: false
        required: false
      KHQ_PROD:
        description: 'KHQ_PROD'
        type: boolean
        default: false
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Display input values
        run: |
          echo "Deploy Environment: ${{ github.event.inputs.DeployEnvironment }}"
          echo "Info Message: ${{ github.event.inputs.InfoMessage }}"
          echo "Deploy to Anonymous: ${{ github.event.inputs.Anonymous }}"
          echo "Deploy to KHQ: ${{ github.event.inputs.KHQ }}"

      - name: Conditional Deployment for PPE to Anonymous
        if: ${{ github.event.inputs.DeployEnvironment == 'PPE' && github.event.inputs.Anonymous == 'true' }}
        run: |
          echo "Deploying to PPE environment for Anonymous customer"
          # Add your deployment steps for PPE Anonymous here

      - name: Conditional Deployment for PROD to KHQ
        if: ${{ github.event.inputs.DeployEnvironment == 'PROD' && github.event.inputs.KHQ == 'true' }}
        run: |
          echo "Deploying to PROD environment for KHQ customer"
          # Add your deployment steps for PROD KHQ here
