name: Manual Trigger Workflow

on:
  workflow_dispatch:
    inputs:
      Message:
        description: 'PPE Deploy'
        type: string
        required: false
      Anonymous:
        description: 'Anonymous'
        type: boolean
        default: false
        required: true

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      
      - name: Print input values
        run: |
          echo "Anonymous input value is: ${{ github.event.inputs.Anonymous }}"
