name: Manual Trigger Workflow

on:
  workflow_dispatch:
    inputs:
      Instructions:
        description: |
          **Instructions:**
          1. Make sure you have the necessary permissions.
          2. Verify the changes you intend to make.
          3. Ensure that the input below is correctly set.
        type: boolean
        default: false
        required: true
      Anonymous:
        description: 'Is the customer anonymous? Set to true if the customer wishes to remain anonymous.'
        type: boolean
        default: false
        required: true

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      
      - name: Print input values
        run: |
          echo "Anonymous input value is: ${{ github.event.inputs.Anonymous }}"
