name: Manual Deploy with Inputs

on:
  workflow_dispatch:
    inputs:
      PPE_Deploy:
        description: 'Deploy to PPE'
        type: boolean
        default: false
        required: false
      PROD_Deploy:
        description: 'Deploy to PROD'
        type: boolean
        default: false
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Display input values
        run: |
          echo "PPE Deployment: ${{ github.event.inputs.PPE_Deploy }}"
          echo "PROD Deployment: ${{ github.event.inputs.PROD_Deploy }}"

      - name: Conditional Deployment for PPE
        if: ${{ github.event.inputs.PPE_Deploy == 'true' }}
        run: |
          echo "Deploying to PPE environment"
          echo "Info Message: ${{ github.event.inputs.InfoMessage }}"
          echo "Anonymous: ${{ github.event.inputs.Anonymous }}"
          # Add your deployment steps for PPE here

      - name: Conditional Deployment for PROD
        if: ${{ github.event.inputs.PROD_Deploy == 'true' }}
        run: |
          echo "Deploying to PROD environment"
          echo "Info Message: ${{ github.event.inputs.InfoMessage }}"
          echo "KHQ: ${{ github.event.inputs.KHQ }}"
          # Add your deployment steps for PROD here
