name: Manual Trigger Workflow

on:
  workflow_dispatch:
    inputs:
      Instructions:
        description: 'Please review the following instructions'
        type: boolean
        default: false
        required: false
      Anonymous:
        description: 'Is the customer anonymous? Set to true if the customer wishes to remain anonymous.'
        type: boolean
        default: false
        required: true

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      
      - name: Print input value
        run: echo "Anonymous input value is"
