name: Manual Deploy with Inputs

on:
  workflow_dispatch:
    inputs:
      Message:
        description: 'Deploy PPE'
        type: string
        default: 'Instructions'
        required: false
      Anonymous:
        description: 'Anonymous'
        type: boolean
        default: false
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Display Inputs
      run: |
        echo "Message: ${{ github.event.inputs.Message }}"
        echo "Anonymous: ${{ github.event.inputs.Anonymous }}"
      
    - name: Conditional Step
      if: ${{ github.event.inputs.Anonymous == 'true' }}
      run: |
        echo "Running in anonymous mode"

    - name: Non-Anonymous Step
      if: ${{ github.event.inputs.Anonymous == 'false' }}
      run: |
        echo "Running with user identification"
