name: Manual Trigger Workflow

on:
  workflow_dispatch:
    # Optional: you can define inputs to be passed when triggering manually
    inputs:
      greeting:
        description: 'A greeting message'
        required: true
        default: 'Hello'

jobs:
  run-manual-job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Print greeting
        run: echo "The greeting message"
