name: Manual Trigger Workflow

on:
  workflow_dispatch:
    inputs:
      Anonymous:
        description: 'Customer Anonymous'
        type: boolean
        default: false
        required: false
    name: 'Trigger Manual Workflow' # This sets the name for the manual trigger

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      
      - name: Print input value
        run: echo "Anonymous input value is"

