name: Manual Deploy with Inputs

on:
  workflow_dispatch:
    inputs:
      PPE_Deploy:
        description: 'Deploy to PPE'
        type: boolean
        default: false
        required: false
      PPE_Customer:
        description: 'Select customer for PPE deployment'
        type: string
        required: false
        default: ''
      PROD_Deploy:
        description: 'Deploy to PROD'
        type: boolean
        default: false
        required: false
      PROD_Customer:
        description: 'Select customer for PROD deployment'
        type: string
        required: false
        default: ''

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Display input values
        run: |
          echo "PPE Deployment: ${{ github.event.inputs.PPE_Deploy }}"
          echo "PPE Customer: ${{ github.event.inputs.PPE_Customer }}"
          echo "PROD Deployment: ${{ github.event.inputs.PROD_Deploy }}"
          echo "PROD Customer: ${{ github.event.inputs.PROD_Customer }}"

      - name: Conditional Deployment for PPE
        if: ${{ github.event.inputs.PPE_Deploy == 'true' && github.event.inputs.PPE_Customer != '' }}
        run: |
          echo "Deploying to PPE environment for selected customer: ${{ github.event.inputs.PPE_Customer }}"
          # Add your deployment steps for PPE here

      - name: Conditional Deployment for PROD
        if: ${{ github.event.inputs.PROD_Deploy == 'true' && github.event.inputs.PROD_Customer != '' }}
        run: |
          echo "Deploying to PROD environment for selected customer: ${{ github.event.inputs.PROD_Customer }}"
          # Add your deployment steps for PROD here
