name: Manual Deploy with Inputs

on:
  workflow_dispatch:
    inputs:
      Info:
        description: 'PPE Deploy'
        type: string
        required: true
      Anonymous:
        description: 'Anonymous'
        type: boolean
        default: false
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Display Start Message
      run: echo "Starting the deployment process..."

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Display Inputs
      run: |
        echo "Info: ${{ github.event.inputs.Info }}"
        echo "Anonymous: ${{ github.event.inputs.Anonymous }}"
      
    - name: Conditional Step
      if: ${{ github.event.inputs.Anonymous }}
      run: |
        echo "Running in anonymous mode"

    - name: Non-Anonymous Step
      if: ${{ !github.event.inputs.Anonymous }}
      run: |
        echo "Running with user identification"
