name: Manual Deploy with Inputs
on: 
  workflow_call:
    inputs:
      deployEnvironment:
        description: 'Environment to deploy to'
        required: true
        type: string
      BuildVersion:
        description: 'Build Version being deployed'
        required: true
        type: string   
      GKECLUSTER: 
        description: 'GKE Cluster to deploy to'
        required: true
        type: string   
      GKEZONE: 
        description: 'GKE zone to deploy to'
        required: true
        type: string   
      PROJECTID: 
        description: 'GCP project name'
        required: true
        type: string
      MIGRATIONS_DIR:
        description: 'Directory with DB migrations project'
        required: true
        type: string
        type: boolean
        default: false
        required: false
      PROD_Customer:
        description: 'PROD deployment'
        type: string
        required: false
        default: 'Select the Customer'
      KHQ_PROD:
        description: 'KHQ_PROD'
        type: boolean
        default: false
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Display input values
        run: |
          echo "PPE Deployment: ${{ github.event.inputs.PPE_Deploy }}"
          echo "PPE Customer: ${{ github.event.inputs.PPE_Customer }}"
          echo "PROD Deployment: ${{ github.event.inputs.PROD_Deploy }}"
          echo "PROD Customer: ${{ github.event.inputs.PROD_Customer }}"

      - name: Conditional Deployment for PPE
        if: ${{ github.event.inputs.PPE_Deploy == 'true' && github.event.inputs.PPE_Customer != '' }}
        run: |
          echo "Deploying to PPE environment for selected customer: ${{ github.event.inputs.PPE_Customer }}"
          # Add your deployment steps for PPE here

      - name: Conditional Deployment for PROD
        if: ${{ github.event.inputs.PROD_Deploy == 'true' && github.event.inputs.PROD_Customer != '' }}
        run: |
          echo "Deploying to PROD environment for selected customer: ${{ github.event.inputs.PROD_Customer }}"
          # Add your deployment steps for PROD here
